require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - '.git/**/*'
    - 'node_modules/**/*'
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Layout/LineLength:
  Max: 130

RSpec/AnyInstance:
  Enabled: false