require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/drafts', type: :request do
  # Draft. As you add validations to Draft, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Draft.create! valid_attributes
      get drafts_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      draft = Draft.create! valid_attributes
      get draft_url(draft)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Draft' do
        expect do
          post drafts_url, params: { draft: valid_attributes }
        end.to change(Draft, :count).by(1)
      end

      it 'redirects to the created draft' do
        post drafts_url, params: { draft: valid_attributes }
        expect(response).to redirect_to(draft_url(Draft.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Draft' do
        expect do
          post drafts_url, params: { draft: invalid_attributes }
        end.to change(Draft, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post drafts_url, params: { draft: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested draft' do
        draft = Draft.create! valid_attributes
        patch draft_url(draft), params: { draft: new_attributes }
        draft.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the draft' do
        draft = Draft.create! valid_attributes
        patch draft_url(draft), params: { draft: new_attributes }
        draft.reload
        expect(response).to redirect_to(draft_url(draft))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        draft = Draft.create! valid_attributes
        patch draft_url(draft), params: { draft: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested draft' do
      draft = Draft.create! valid_attributes
      expect do
        delete draft_url(draft)
      end.to change(Draft, :count).by(-1)
    end

    it 'redirects to the drafts list' do
      draft = Draft.create! valid_attributes
      delete draft_url(draft)
      expect(response).to redirect_to(drafts_url)
    end
  end
end
